[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs =
    .git
    .venv
    venv
    env
    __pycache__
    .pytest_cache
    .mypy_cache
    .ruff_cache
    *backup*
    *-bkp
    repository_archive
addopts = -ra
